FROM python:3-slim

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

 
# Isolated dedicated workspace
WORKDIR /app

# Create a non-privileged user that the app will run under.
ARG UID=10002
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser
    

# Copy the dependencies and install.
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Switch to the non-privileged user to run the application.
USER appuser


# Copy source code in worker and proto folder
COPY --chown=appuser:appuser ./master ./master
COPY --chown=appuser:appuser ./proto ./proto

# Document that the FastAPI server listens on port 8000
EXPOSE 8000

# Spin up the Uvicorn ASGI server targeting the nested main file
CMD ["uvicorn", "master.main:app", "--host", "0.0.0.0", "--port", "8000"]
