FROM python:3-slim

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

# Redirect PyTorch framework caches into our active working space
ENV TORCH_HOME=/app/.cache/torch
 
# Isolated dedicated workspace
WORKDIR /app

# Create a non-privileged user that the app will run under.
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser
    

# Copy the dependencies and install.
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/.cache/torch && chown -R appuser:appuser /app/.cache

# Switch to the non-privileged user to run the application.
USER appuser


# Copy source code in worker and proto folder
COPY --chown=appuser:appuser ./worker ./worker
COPY --chown=appuser:appuser ./proto ./proto
COPY --chown=appuser:appuser ./data/labels ./data/labels

# Expose the port that the application listens on.
EXPOSE 50051

# Run the application.
CMD ["python", "worker/server.py"]