# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"&\n\x10InferenceRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\";\n\x11InferenceResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32X\n\x10InferenceService\x12\x44\n\x07Predict\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=30
  _globals['_INFERENCEREQUEST']._serialized_end=68
  _globals['_INFERENCERESPONSE']._serialized_start=70
  _globals['_INFERENCERESPONSE']._serialized_end=129
  _globals['_INFERENCESERVICE']._serialized_start=131
  _globals['_INFERENCESERVICE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
